name: SecondPipelineForGeoServerDatadir

trigger: none

#This pipeline will be trigged by the GeoServer-Datadir-Save-Staging
resources:
  pipelines:
  - pipeline: GeoServer datadir update with git # Name of the pipeline resource.
    source: GeoServer-Datadir-Save-Staging # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run GeoServer-Datadir-Update-Live pipeline when any run of GeoServer-Datadir-Save-Staging completes

pool:
   name: Live Cluster
stages:
  - stage: pulldatadirchanges
    displayName: Pull Datadir Changes on Live Servers
    jobs:
    - deployment: pulldatadir
      displayName: Pull Datadir Changes
      environment:
       name: Live
       resourceType: VirtualMachine
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               date
               hostname
               cd /mnt/data_dir/
               git checkout --track dorset/main
               git add .
               git commit -a
               git stash
               git fetch --all
               docker-compose stop geoserver
               sleep 30
               git checkout --track dorset/datadir-test
               git pull dorset datadir-test
               git status
               cd /home/dorset/docker-geoserver
               docker-compose up -d --force-recreate geoserver
               sleep 60
               date
              displayName: Updating Datadirs on Live Servers
