name: SecondPipeline

trigger: none

#This pipeline will be trigged by the GeoServer-Datadir-Save-Staging
resources:
  pipelines:
  - pipeline: GeoServer datadir update with git # Name of the pipeline resource.
    source: GeoServer-Datadir-Update-Staging # The name of the pipeline referenced by this pipeline resource.
    project: FabrikamProject # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes



pool:
   name: Live Cluster
stages:
  - stage: pulldatadirchanges
    displayName: Pull Datadir Changes on Live Servers
    jobs:
    - deployment: pulldatadir
      displayName: Pull Datadir Changes
      environment:
       name: Live
       resourceType: VirtualMachine
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               hostname
               cd /mnt/data_dir/
               git add .
               git commit -a
               git stash
               git fetch --all
               git checkout --track dorset/datadir-test
               git pull dorset datadir-test
               git status
              displayName: Updating Datadirs on Live Servers
