name: SecondPipelineForGeoServerDatadir

trigger: none

#This pipeline will be trigged by the GeoServer-Datadir-Save-Staging
resources:
  pipelines:
  - pipeline: GeoServer datadir update with git # Name of the pipeline resource.
    source: GeoServer-Datadir-Save-Staging # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run GeoServer-Datadir-Update-Live pipeline when any run of GeoServer-Datadir-Save-Staging completes

pool:
   name: Live Cluster
stages:
  - stage: pulldatadirchanges
    displayName: Pull Datadir Changes on Live Servers
    jobs:
    - deployment: pulldatadir
      displayName: Pull Datadir Changes
      environment:
       name: Live
       resourceType: VirtualMachine
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               date
               hostname
               cd /mnt/data_dir/
               
               echo "committing local changes to a 'backup' branch"
               git checkout "datadir-backup"
               git add .
               git commit -a
               
               # echo "stashing any uncommitted file"
               # git stash
               git fetch --all
               echo "stopping geoserver"
               docker-compose stop geoserver
               
               echo "waiting for geoserver to stop"
               sleep 30
               
               echo "pulling datadir updates from Azure DevOps"
               git checkout "datadir"
               git pull dorset "datadir"
               git status
               
               echo "restarting geoserver"
               cd /home/dorset/docker-geoserver
               docker-compose up -d --force-recreate geoserver

              echo "testing geoserver"
              curl --fail --connect-timeout '60' --max-time '120' 'localhost:8080/geoserver/styles/raster.xml' | grep StyleInfoImpl
              date
              displayName: Updating Datadirs on Live Servers
